# Generated by Django 3.1 on 2022-02-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimages',
            name='desc',
            field=models.TextField(default='bad'),
        ),
        migrations.AlterField(
            model_name='bannerimages',
            name='image',
            field=models.ImageField(upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='bannerimages',
            name='title',
            field=models.CharField(default='good', max_length=200),
        ),
    ]
