# Generated by Django 3.1 on 2022-02-21 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_auto_20220221_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimages',
            name='desc',
            field=models.TextField(blank='True', default='Special For Today'),
        ),
    ]
