# Generated by Django 3.1 on 2022-02-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='banner_bottom',
        ),
        migrations.AddField(
            model_name='setting',
            name='banner_bottom1',
            field=models.ImageField(default='banner/ab_pic.jpg', upload_to='settings/'),
        ),
        migrations.AddField(
            model_name='setting',
            name='banner_bottom2',
            field=models.ImageField(default='banner/ab_pic.jpg', upload_to='settings/'),
        ),
    ]
