# Generated by Django 3.1 on 2022-02-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20220221_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='contactbanner',
            field=models.ImageField(default='banner/ab_pic.jpg', upload_to='banner/'),
        ),
    ]
