# Generated by Django 3.1 on 2022-02-21 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_setting_contactbanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='bannerbottom1',
            field=models.ImageField(default='banner/ab_pic.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='setting',
            name='bannerbottom2',
            field=models.ImageField(default='banner/ab_pic.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='setting',
            name='bannerlast1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='setting',
            name='bannerlast2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='setting',
            name='contactbanner',
            field=models.ImageField(default='banner/ab_pic.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='setting',
            name='schedulebottom',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='setting',
            name='trending1',
            field=models.ImageField(upload_to='', verbose_name='settings/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='trending2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='setting',
            name='trending3',
            field=models.ImageField(upload_to=''),
        ),
    ]
