# Generated by Django 3.1 on 2022-02-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_auto_20220221_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='trending1',
            field=models.ImageField(upload_to=''),
        ),
    ]
